import type { Extraction } from "./types";

export type SampleSpec = {
  id: string;
  schemaId: string;
  gold: Extraction;
  app: Extraction;
  notes: string;
  pdfTitle: string;
  pdfLines: string[];
};

export const SAMPLES: SampleSpec[] = [
  {
    id: "ADPA7005CHIP",
    schemaId: "RF Amplifier",
    notes:
      "Beispiel aus der Thesis-App. App-JSON hat Pdiss als Absolut-Maximum 13.4 W; Gold nutzt den typischen Betrieb 6 W (5 V × 1.2 A).",
    pdfTitle: "ADPA7005CHIP — GaAs pHEMT MMIC Power Amplifier",
    gold: {
      ComponentType: "RF Amplifier",
      PartNumber: "ADPA7005CHIP",
      Manufacturer: "Analog Devices",
      Description: "GaAs, pHEMT, MMIC, 1 W Power Amplifier, 20 GHz to 44 GHz",
      Function: "Radio Frequency Amplifier",
      PackageType: "DIE-12",
      FMinHz: "20 GHz",
      NumberOfPin: "12",
      FMaxHz: "44 GHz",
      Pitch: "nicht gefunden",
      GainTypDb: "17 dB",
      VsSpecifV: "5 V",
      Op1DbDbm: "30.5 dBm",
      IsupplyMaxA: "1.2 A",
      Oip3TypDbm: "41 dBm",
      PdissW: "6 W",
      NfTypDb: "7 dB",
      SpecifiedHz: "34 GHz",
      RfinMaxDbm: "27 dBm",
      ManufacturerInfo: "Analog Devices",
      ComponentCategory: "RF Power Amplifier",
    },
    app: {
      ComponentType: "RF Amplifier",
      PartNumber: "ADPA7005CHIP",
      Manufacturer: "Analog Devices",
      Description: "GaAs, pHEMT, MMIC, 1 W Power Amplifier, 20 GHz to 44 GHz",
      Function: "Radio Frequency Amplifier",
      PackageType: "DIE-12",
      FMinHz: "20 GHz",
      NumberOfPin: "12",
      FMaxHz: "44 GHz",
      Pitch: "nicht gefunden",
      GainTypDb: "17 dB",
      VsSpecifV: "5 V",
      Op1DbDbm: "30.5 dBm",
      IsupplyMaxA: "1.2 A",
      Oip3TypDbm: "41 dBm",
      PdissW: "13.4 W",
      NfTypDb: "7 dB",
      SpecifiedHz: "34 GHz",
      RfinMaxDbm: "27 dBm",
      ManufacturerInfo: "Analog Devices",
      ComponentCategory: "RF Power Amplifier",
    },
    pdfLines: [
      "Analog Devices ADPA7005CHIP",
      "GaAs, pHEMT, MMIC, 1 W Power Amplifier, 20 GHz to 44 GHz",
      "Function: Radio Frequency Amplifier",
      "Package type: DIE-12",
      "Number of pins: 12",
      "Frequency range: 20 GHz to 44 GHz",
      "Gain: 17 dB typical at 22 GHz to 34 GHz",
      "Output P1dB: 30.5 dBm typical at 22 GHz to 34 GHz",
      "Output IP3: 41 dBm typical at 22 GHz to 34 GHz",
      "Noise figure: 7 dB typical",
      "Supply voltage VDD: 5 V",
      "Supply current IDQ: 1.2 A (1200 mA)",
      "Power dissipation (typical): 6 W",
      "Continuous power dissipation (absolute maximum, T = 85 C): 13.4 W",
      "RF input power RFIN absolute maximum: 27 dBm",
      "Specified at: 34 GHz",
    ],
  },
  {
    id: "HMC1131",
    schemaId: "RF Amplifier",
    notes: "Zweites RF-PA-Beispiel, Gold = App (bereits geprüft).",
    pdfTitle: "HMC1131 — GaAs pHEMT MMIC Power Amplifier",
    gold: {
      ComponentType: "RF Amplifier",
      PartNumber: "HMC1131",
      Manufacturer: "Analog Devices",
      Description: "GaAs pHEMT MMIC 0.5 W Power Amplifier, 24 GHz to 35 GHz",
      Function: "Radio Frequency Amplifier",
      PackageType: "LP4-16",
      FMinHz: "24 GHz",
      NumberOfPin: "16",
      FMaxHz: "35 GHz",
      Pitch: "0.5 mm",
      GainTypDb: "24 dB",
      VsSpecifV: "5 V",
      Op1DbDbm: "26 dBm",
      IsupplyMaxA: "0.35 A",
      Oip3TypDbm: "35 dBm",
      PdissW: "1.8 W",
      NfTypDb: "5.5 dB",
      SpecifiedHz: "30 GHz",
      RfinMaxDbm: "20 dBm",
      ManufacturerInfo: "Analog Devices",
      ComponentCategory: "RF Power Amplifier",
    },
    app: {
      ComponentType: "RF Amplifier",
      PartNumber: "HMC1131",
      Manufacturer: "Analog Devices",
      Description: "GaAs pHEMT MMIC 0.5 W Power Amplifier, 24 GHz to 35 GHz",
      Function: "Radio Frequency Amplifier",
      PackageType: "LP4-16",
      FMinHz: "24 GHz",
      NumberOfPin: "16",
      FMaxHz: "35 GHz",
      Pitch: "0.5 mm",
      GainTypDb: "22 dB",
      VsSpecifV: "5 V",
      Op1DbDbm: "26 dBm",
      IsupplyMaxA: "0.35 A",
      Oip3TypDbm: "35 dBm",
      PdissW: "1.8 W",
      NfTypDb: "5.5 dB",
      SpecifiedHz: "30 GHz",
      RfinMaxDbm: "20 dBm",
      ManufacturerInfo: "Analog Devices",
      ComponentCategory: "RF Power Amplifier",
    },
    pdfLines: [
      "Analog Devices HMC1131",
      "GaAs pHEMT MMIC 0.5 W Power Amplifier, 24 GHz to 35 GHz",
      "Package type: LP4-16",
      "Number of pins: 16",
      "Pitch: 0.5 mm",
      "Frequency range: 24 GHz to 35 GHz",
      "Gain: 24 dB typical",
      "Output P1dB: 26 dBm typical",
      "Output IP3: 35 dBm typical",
      "Noise figure: 5.5 dB",
      "Supply voltage: 5 V",
      "Supply current IDQ: 0.35 A",
      "Power dissipation: 1.8 W",
      "RF input power absolute maximum: 20 dBm",
      "Specified at: 30 GHz",
    ],
  },
  {
    id: "QPA2213",
    schemaId: "RF Amplifier",
    notes: "",
    pdfTitle: "QPA2213 — 2–20 GHz GaN Power Amplifier",
    gold: {
      ComponentType: "RF Amplifier",
      PartNumber: "QPA2213",
      Manufacturer: "Qorvo",
      Description: "2 GHz to 20 GHz 2 W GaN Power Amplifier",
      Function: "Radio Frequency Amplifier",
      PackageType: "QFN-32",
      FMinHz: "2 GHz",
      NumberOfPin: "32",
      FMaxHz: "20 GHz",
      Pitch: "0.5 mm",
      GainTypDb: "16 dB",
      VsSpecifV: "20 V",
      Op1DbDbm: "33 dBm",
      IsupplyMaxA: "0.45 A",
      Oip3TypDbm: "43 dBm",
      PdissW: "9 W",
      NfTypDb: "4.5 dB",
      SpecifiedHz: "10 GHz",
      RfinMaxDbm: "23 dBm",
      ManufacturerInfo: "Qorvo",
      ComponentCategory: "RF Power Amplifier",
    },
    app: {
      ComponentType: "RF Amplifier",
      PartNumber: "QPA2213",
      Manufacturer: "Qorvo",
      Description: "2 GHz to 20 GHz 2 W GaN Power Amplifier",
      Function: "Radio Frequency Amplifier",
      PackageType: "QFN-32",
      FMinHz: "2 GHz",
      NumberOfPin: "32",
      FMaxHz: "20 GHz",
      Pitch: "0.5 mm",
      GainTypDb: "16 dB",
      VsSpecifV: "20 V",
      Op1DbDbm: "33 dBm",
      IsupplyMaxA: "0.45 A",
      Oip3TypDbm: "43 dBm",
      PdissW: "9 W",
      NfTypDb: "4.5 dB",
      SpecifiedHz: "10 GHz",
      RfinMaxDbm: "23 dBm",
      ManufacturerInfo: "Qorvo",
      ComponentCategory: "RF Power Amplifier",
    },
    pdfLines: [
      "Qorvo QPA2213",
      "2 GHz to 20 GHz 2 W GaN Power Amplifier",
      "Package type: QFN-32",
      "Number of pins: 32",
      "Pitch: 0.5 mm",
      "Frequency range: 2 GHz to 20 GHz",
      "Gain: 16 dB typical",
      "Output P1dB: 33 dBm typical",
      "Output IP3: 43 dBm typical",
      "Noise figure: 4.5 dB",
      "Supply voltage VDD: 20 V",
      "Supply current: 0.45 A",
      "Power dissipation: 9 W",
      "RF input absolute maximum: 23 dBm",
      "Specified at: 10 GHz",
    ],
  },
  {
    id: "AD8421",
    schemaId: "Operational Amplifier",
    notes: "",
    pdfTitle: "AD8421 — Low Noise Instrumentation Amplifier",
    gold: {
      ComponentType: "Operational Amplifier",
      PartNumber: "AD8421",
      Manufacturer: "Analog Devices",
      Description: "Low Noise, Low Power Instrumentation Amplifier",
      PackageType: "SOIC-8",
      NumberOfPin: "8",
      VsMinV: "±2.5 V",
      VsMaxV: "±18 V",
      IqTypA: "2.3 mA",
      GbwHz: "10 MHz",
      SlewRateVus: "35 V/us",
      VosTypV: "25 uV",
      IbTypA: "0.1 nA",
      RailToRail: "nein",
      ComponentCategory: "Instrumentation Amplifier",
    },
    app: {
      ComponentType: "Operational Amplifier",
      PartNumber: "AD8421",
      Manufacturer: "Analog Devices",
      Description: "Low Noise, Low Power Instrumentation Amplifier",
      PackageType: "SOIC-8",
      NumberOfPin: "8",
      VsMinV: "±2.5 V",
      VsMaxV: "±18 V",
      IqTypA: "2.3 mA",
      GbwHz: "10 MHz",
      SlewRateVus: "35 V/us",
      VosTypV: "50 uV",
      IbTypA: "0.1 nA",
      RailToRail: "nein",
      ComponentCategory: "Instrumentation Amplifier",
    },
    pdfLines: [
      "Analog Devices AD8421",
      "Low Noise, Low Power Instrumentation Amplifier",
      "Package type: SOIC-8",
      "Number of pins: 8",
      "Supply voltage: 2.5 V to 18 V (dual ±2.5 V to ±18 V)",
      "Quiescent current: 2.3 mA typical",
      "Gain bandwidth: 10 MHz",
      "Slew rate: 35 V/us",
      "Offset voltage Vos: 25 uV typical",
      "Input bias current: 0.1 nA",
      "Rail-to-rail: no",
    ],
  },
  {
    id: "OPA2210",
    schemaId: "Operational Amplifier",
    notes: "",
    pdfTitle: "OPA2210 — Precision Op Amp",
    gold: {
      ComponentType: "Operational Amplifier",
      PartNumber: "OPA2210",
      Manufacturer: "Texas Instruments",
      Description: "2.2 nV/√Hz Precision, Low-Power Op Amp",
      PackageType: "VSSOP-8",
      NumberOfPin: "8",
      VsMinV: "4.5 V",
      VsMaxV: "36 V",
      IqTypA: "2.5 mA",
      GbwHz: "18 MHz",
      SlewRateVus: "6.4 V/us",
      VosTypV: "5 uV",
      IbTypA: "0.3 nA",
      RailToRail: "Ausgang",
      ComponentCategory: "Precision Op Amp",
    },
    app: {
      ComponentType: "Operational Amplifier",
      PartNumber: "OPA2210",
      Manufacturer: "Texas Instruments",
      Description: "2.2 nV/√Hz Precision, Low-Power Op Amp",
      PackageType: "VSSOP-8",
      NumberOfPin: "8",
      VsMinV: "4.5 V",
      VsMaxV: "36 V",
      IqTypA: "2.5 mA",
      GbwHz: "18 MHz",
      SlewRateVus: "6.4 V/us",
      VosTypV: "5 uV",
      IbTypA: "0.3 nA",
      RailToRail: "Ausgang",
      ComponentCategory: "Precision Op Amp",
    },
    pdfLines: [
      "Texas Instruments OPA2210",
      "2.2 nV/sqrt(Hz) Precision, Low-Power Op Amp",
      "Package type: VSSOP-8",
      "Number of pins: 8",
      "Supply voltage: 4.5 V to 36 V",
      "Quiescent current: 2.5 mA typical",
      "Gain bandwidth: 18 MHz",
      "Slew rate: 6.4 V/us",
      "Offset voltage Vos: 5 uV typical",
      "Input bias current: 0.3 nA",
      "Rail-to-rail: output",
    ],
  },
  {
    id: "ADRF5020",
    schemaId: "RF Switch",
    notes: "",
    pdfTitle: "ADRF5020 — Silicon SPDT Switch",
    gold: {
      ComponentType: "RF Switch",
      PartNumber: "ADRF5020",
      Manufacturer: "Analog Devices",
      Description: "100 MHz to 30 GHz Silicon SPDT Switch",
      PackageType: "LFCSP-20",
      FMinHz: "100 MHz",
      FMaxHz: "30 GHz",
      IlTypDb: "2.0 dB",
      IsolationTypDb: "60 dB",
      P1dBDbm: "28 dBm",
      Ip3Dbm: "53 dBm",
      SwitchingNs: "10 ns",
      Configuration: "SPDT",
      ComponentCategory: "RF Switch",
    },
    app: {
      ComponentType: "RF Switch",
      PartNumber: "ADRF5020",
      Manufacturer: "Analog Devices",
      Description: "100 MHz to 30 GHz Silicon SPDT Switch",
      PackageType: "LFCSP-20",
      FMinHz: "100 MHz",
      FMaxHz: "30 GHz",
      IlTypDb: "2.0 dB",
      IsolationTypDb: "60 dB",
      P1dBDbm: "28 dBm",
      Ip3Dbm: "53 dBm",
      SwitchingNs: "10 ns",
      Configuration: "SPDT",
      ComponentCategory: "RF Switch",
    },
    pdfLines: [
      "Analog Devices ADRF5020",
      "100 MHz to 30 GHz Silicon SPDT Switch",
      "Package type: LFCSP-20",
      "Configuration: SPDT",
      "Frequency range: 100 MHz to 30 GHz",
      "Insertion loss: 2.0 dB typical",
      "Isolation: 60 dB typical",
      "Input P1dB: 28 dBm",
      "IP3: 53 dBm",
      "Switching time: 10 ns",
    ],
  },
  {
    id: "HMC1118",
    schemaId: "RF Switch",
    notes: "",
    pdfTitle: "HMC1118 — High Isolation SPDT",
    gold: {
      ComponentType: "RF Switch",
      PartNumber: "HMC1118",
      Manufacturer: "Analog Devices",
      Description: "9 kHz to 13.0 GHz Silicon SPDT Switch",
      PackageType: "LFCSP-16",
      FMinHz: "9 kHz",
      FMaxHz: "13 GHz",
      IlTypDb: "0.8 dB",
      IsolationTypDb: "50 dB",
      P1dBDbm: "33 dBm",
      Ip3Dbm: "60 dBm",
      SwitchingNs: "150 ns",
      Configuration: "SPDT",
      ComponentCategory: "RF Switch",
    },
    app: {
      ComponentType: "RF Switch",
      PartNumber: "HMC1118",
      Manufacturer: "Analog Devices",
      Description: "9 kHz to 13.0 GHz Silicon SPDT Switch",
      PackageType: "LFCSP-16",
      FMinHz: "9 kHz",
      FMaxHz: "13 GHz",
      IlTypDb: "1.2 dB",
      IsolationTypDb: "50 dB",
      P1dBDbm: "33 dBm",
      Ip3Dbm: "60 dBm",
      SwitchingNs: "150 ns",
      Configuration: "SPDT",
      ComponentCategory: "RF Switch",
    },
    pdfLines: [
      "Analog Devices HMC1118",
      "9 kHz to 13.0 GHz Silicon SPDT Switch",
      "Package type: LFCSP-16",
      "Configuration: SPDT",
      "Frequency range: 9 kHz to 13 GHz",
      "Insertion loss: 0.8 dB typical",
      "Isolation: 50 dB typical",
      "Input P1dB: 33 dBm",
      "IP3: 60 dBm",
      "Switching time: 150 ns",
    ],
  },
];
